In [6]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [8]:
df.to_csv('data_missing.csv',index=False)

In [10]:
pd.read_csv('data_missing.csv')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [12]:
import numpy as np
import pandas as pd
Data1={'Names':['Ramesh','Suresh','Sathish',None],
     'Age':[None,22,25,27],
     'City':['Pune','Pune',None,'Hyd']}
df1=pd.DataFrame(Data1)
df1

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [14]:
df1.to_csv('data_missing1.csv',index=False)

In [16]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [18]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

**isnull**

In [21]:
df.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [23]:
df1.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [25]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [27]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [30]:
df.fillna(30)

Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

In [32]:
df1.fillna(30)

Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

- the above one is we are filling randomly

- all the columns are filled with random number

- It is not a good approach because in a data we have different data types

In [35]:
df.fillna('Hyd')

Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

In [37]:
df1.fillna('Hyd')

Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

**What is the difference between np.nan and None**

In [40]:
np.nan+5

nan

In [42]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [44]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [46]:
arr1

array([ 1.,  2., nan,  3.])

In [50]:
arr2

array([1, 2, None, 3], dtype=object)

In [56]:
np.nansum(arr1),np.sum(arr1)

(6.0, nan)

In [60]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents **float type**

- None represents **Object type**

- if data operations related to Maths then nan format is better

**Fill the value based on column**

In [66]:
#df.fillna()
df['Names'].fillna('Manish')

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

In [68]:
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [70]:
df['Age'].fillna(20)

0    20.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [72]:
df['Age'].fillna('20')

0      20
1    22.0
2    25.0
3    27.0
Name: Age, dtype: object

In [76]:
df['Age'].fillna(20).values

array([20., 22., 25., 27.])

In [78]:
df['Age'].fillna('20').values

array(['20', 22.0, 25.0, 27.0], dtype=object)

In [80]:
df['Age1']=df['Age'].fillna(20).values
df['Age2']=df['Age'].fillna('20').values

In [82]:
df

Names   Age  City  Age1  Age2
0   Ramesh   NaN  Pune  20.0    20
1   Suresh  22.0  Pune  22.0  22.0
2  Sathish  25.0   NaN  25.0  25.0
3      NaN  27.0   Hyd  27.0  27.0

In [84]:
df.dtypes

Names     object
Age      float64
City      object
Age1     float64
Age2      object
dtype: object

- because of one value total data type is changed

- we can convert one data type column to another data type  **astype**

In [91]:
df['Age2']=df['Age2'].astype('float')

In [93]:
df.dtypes

Names     object
Age      float64
City      object
Age1     float64
Age2     float64
dtype: object

**Fill with Method**

In [96]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

- pad

- bfill

- ffill

- backfill


In [ ]:
df.fillna(method='pad')

In [107]:
s='U+200B (ZERO WIDTH SPACE)'
s1=''
for i in s:
    if i.isdigit():
        s1=s1+i
int(s1)

200

In [111]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [113]:
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [115]:
df.fillna(method='pad',axis=1)

Names     Age  City
0   Ramesh  Ramesh  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

In [ ]:
# pad-ffill
# bfill-backfill

**Mean-Median-Mode**

- insted of filling with random values

- we can use mean median and mode also

- For Numerical columns use mean and Median

    - if Data outliers are there use **Median**

- For categorical columns use **Mode**

In [124]:
# First calculate median
# Then fill with median
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [128]:
round(df['Age'].mean(),2)

24.67

**KNNImputer**

- KNN: K nearest neigbours

- instead of taking all the data values average

- we can take only specific values average

- thats why the name is called as Nearest Neighbours

- Hyper parameter: the argument which user can provide

- here k is hyper parameter

- which means the user can decide how many neighbours he can choose

- it is under **sklearn**

    - class name **imputer**

        - method name **KNNImputer**

In [136]:
data1={'A':[1,2,3,4,5,np.nan,7],
      'B':[11,22,np.nan,47,55,77,7],
      'C':[21,10,3,4,np.nan,66,7]}
df2=pd.DataFrame(data1)

In [146]:
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=2)
knn.fit_transform(df2)

array([[ 1. , 11. , 21. ],
       [ 2. , 22. , 10. ],
       [ 3. , 51. ,  3. ],
       [ 4. , 47. ,  4. ],
       [ 5. , 55. ,  3.5],
       [ 4.5, 77. , 66. ],
       [ 7. ,  7. ,  7. ]])

In [142]:
(4+5+7)/3

5.333333333333333

In [144]:
(1+2+7)/3

3.3333333333333335

- How it is deciding neigbours: Euclidian distance

- give the categorical data : It is works or not

In [ ]:
10days individual
1day 2hours 
bullets
wed sql 
transforamtions